version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.1-ce-rc2-git
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: docker build . -t cumuluss/circleci:node-8.11
      - run:
          name: Build docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin 
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push cumuluss/circleci:node-8.11
            fi
            