version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.1-ce-rc2-git
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Build docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build . -t cumuluss/circleci:node-6.10
