version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.1-ce-rc2-git
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build . -t cumuluss/circleci:node-6.10
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push cumuluss/circleci:node-6.10
            fi
            